<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <GhulCompiler>dotnet ghul-compiler</GhulCompiler>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ghul.runtime" />
    <GhulSources Include="src/**/*.ghul" />
  </ItemGroup>
</Project>